server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flex
    username: postgres
    password: pings
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always